services:
  nextjs-app:
    build: .
    container_name: karma_kanban_app
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: kkplus_local_db
    environment:
      POSTGRES_USER: kkplus_user
      POSTGRES_PASSWORD: kkplus_pass
      POSTGRES_DB: kkplus_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: kkplus_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
