services:
  nextjs-app:
    build: .
    container_name: karma_kanban_app
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: kkplus_local_db # Nombre del contenedor (se puede personalizar)
    environment:
      POSTGRES_USER: kkplus_user # Usuario de la base de datos (se puede personalizar)
      POSTGRES_PASSWORD: kkplus_pass # Contraseña del usuario (se puede personalizar)
      POSTGRES_DB: kkplus_db # Nombre de la base de datos (se puede personalizar)
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: kkplus_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com # Cambia esto por tu correo
      PGADMIN_DEFAULT_PASSWORD: admin123 # Cambia esto por tu contraseña
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
